#spring.application.name=backend
#spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:49960/railway
#spring.datasource.username=root
#spring.datasource.password=FKKwbwSGjciQZmdKtMzuQoZSlwnxYPfb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format-sql=true
#logging.level.org.springframework.validation=DEBUG
#logging.level.org.springframework.web=DEBUG
#spring.application.name=backend

#2nd Deploy
spring.application.name=backend
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:55351/railway
spring.datasource.username=root
spring.datasource.password=BdxdpqrAeuiXZzWKXzzlofXgPHRUCURs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
logging.level.org.springframework.validation=DEBUG
logging.level.org.springframework.web=DEBUG


#Local Deploy
#spring.application.name=backend
#spring.datasource.url=jdbc:mysql://localhost:3306/bangladesh2_0
#spring.datasource.username=root
#spring.datasource.password=shanto1
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format-sql=true
#logging.level.org.springframework.validation=DEBUG
#logging.level.org.springframework.web=DEBUG

#server.servlet.context-path=/api

jwt.secrectkey=askjfbawfour234198fjhrjhetbu4yg78321iu4jhjhsadbjhgfuyg4389b32ui09yzqs

